apiVersion: logging.custom/v1alpha1
kind: Logstash
metadata:
  name: example-logstash
spec:
  applications:
  - name: logging-sample-1
    patterns:
      INFO: info
      DEBUG: debug
    matchers:
    - "%{INFO:info} %{GREEDYDATA:rest}"
    - "%{DEBUG:debug} %{GREEDYDATA:rest}"
  - name: logging-sample-2
    patterns:
      WARN: warn
      ERROR: error
    matchers:
    - "%{WARN:warn} %{GREEDYDATA:rest}"
    - "%{ERROR:error} %{GREEDYDATA:rest}"
