apiVersion: logging.custom/v1alpha1
kind: Logstash
metadata:
  name: example-logstash
spec:
  applications:
  - name: app-1
    patterns:
      WARN: warn
      TEST: test
    matchers:
      # MATCHER: "match => { 'message' => '%{WARN:warn} %{GREEDYDATA:rest}' }"
      WARN-MATCHER: "%{WARN:warn} %{GREEDYDATA:rest}"
      TEST-MATCHER: "%{TEST:test} %{GREEDYDATA:rest}"
  - name: app-2
    patterns:
      DEBUG: debug
    matchers:
      # MATCHER: "match => { 'message' => '%{DEBUG:debug} %{GREEDYDATA:rest}' }"
      MATCHER: "%{DEBUG:debug} %{GREEDYDATA:rest}"
      
  # pattern:
  #   WARN: warn
  #   DEBUG: debug
  # spec:
  # Add fields here
  # size: 3
