kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logstash-operator
subjects:
- kind: ServiceAccount
  name: logstash-operator
  namespace: grayskull-logs
roleRef:
  kind: ClusterRole
  name: logstash-operator
  apiGroup: rbac.authorization.k8s.io
