apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logstash-operator
  template:
    metadata:
      labels:
        name: logstash-operator
    spec:
      serviceAccountName: logstash-operator
      containers:
        - name: logstash-operator
          image: quay.io/njbarber/logstash-operator:v0.0.1
          command:
          - logstash-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "logstash-operator"
