// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.Logstash":       schema_pkg_apis_logging_v1alpha1_Logstash(ref),
		"github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashSpec":   schema_pkg_apis_logging_v1alpha1_LogstashSpec(ref),
		"github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashStatus": schema_pkg_apis_logging_v1alpha1_LogstashStatus(ref),
	}
}

func schema_pkg_apis_logging_v1alpha1_Logstash(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Logstash is the Schema for the logstashes API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashSpec", "github.com/njbarber/logstash-operator/pkg/apis/logging/v1alpha1.LogstashStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_logging_v1alpha1_LogstashSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LogstashSpec defines the desired state of Logstash",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_logging_v1alpha1_LogstashStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LogstashStatus defines the observed state of Logstash",
				Type:        []string{"object"},
			},
		},
	}
}
